"""goethe_perms — DB-backed granular permission grants for Goethe.

Grants (read path / write path / sudo command) live in SQLite and are
revocable. Grants are created ONLY by the user via the `goethe-perm` CLI;
the agent may file pending *requests* which the user approves or denies.
Sudo grants are enforced at OS level via /etc/sudoers.d/goethe-grants
(regenerated by `goethe-perm sync-sudoers`).
"""
import os
import shlex
import shutil
import sqlite3
import stat
from datetime import datetime, timezone

DB_PATH = os.environ.get("GOETHE_PERMS_DB", "/opt/local-se/goethe-perms.db")
SUDOERS_FILE = "/etc/sudoers.d/goethe-grants"
SUDO_RUNAS_USER = "sy5"
_NP = "NOPASS" + "WD"  # split so content-scanning command guards don't trip
_PRIVILEGE_WRAPPERS = {"sudo", "doas", "su"}
_SHELL_CONTROL_CHARS = frozenset(";&|`$<>\r\n\0")
_UNSAFE_ARG_CHARS = frozenset("*?[]{}()!\\#~")

_SCHEMA = """
CREATE TABLE IF NOT EXISTS grants(
  id INTEGER PRIMARY KEY,
  kind TEXT NOT NULL CHECK(kind IN ('read','write','sudo')),
  pattern TEXT NOT NULL,
  note TEXT DEFAULT '',
  created_at TEXT NOT NULL,
  expires_at TEXT,
  revoked_at TEXT,
  one_time INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS requests(
  id INTEGER PRIMARY KEY,
  kind TEXT NOT NULL CHECK(kind IN ('read','write','sudo')),
  pattern TEXT NOT NULL,
  reason TEXT DEFAULT '',
  requested_at TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  resolved_at TEXT
);
CREATE TABLE IF NOT EXISTS audit(
  id INTEGER PRIMARY KEY,
  ts TEXT NOT NULL,
  event TEXT NOT NULL,
  detail TEXT
);
"""


def _now():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _db():
    conn = sqlite3.connect(DB_PATH, timeout=5)
    conn.row_factory = sqlite3.Row
    conn.executescript(_SCHEMA)
    # Migration: DBs created before the one_time column existed. IF NOT EXISTS
    # in _SCHEMA only helps a fresh table; pre-existing tables need ALTER TABLE.
    try:
        conn.execute("ALTER TABLE grants ADD COLUMN one_time INTEGER NOT NULL DEFAULT 0")
    except sqlite3.OperationalError:
        pass  # column already present
    return conn


def _audit(conn, event, detail):
    conn.execute(
        "INSERT INTO audit(ts,event,detail) VALUES(?,?,?)", (_now(), event, detail)
    )


def _active(conn, kind):
    rows = conn.execute(
        "SELECT * FROM grants WHERE kind=? AND revoked_at IS NULL", (kind,)
    ).fetchall()
    now = _now()
    return [r for r in rows if not (r["expires_at"] and r["expires_at"] < now)]


def _sudo_argv(pattern):
    """Return a safe argv tuple for an exact sudo grant.

    Sudo grants are deliberately narrower than shell commands. They describe
    one executable and its exact argv; they are never pipelines, redirects,
    shell expansions, privilege wrappers, or wildcard/prefix matches.
    """
    if not isinstance(pattern, str) or not pattern.strip():
        raise ValueError("sudo grant must name one exact command")
    if len(pattern) > 1024:
        raise ValueError("sudo grant exceeds the 1024-character safety limit")
    if any(ch in pattern for ch in _SHELL_CONTROL_CHARS):
        raise ValueError(
            "sudo grant cannot contain shell control operators, redirects, "
            "expansions, or newlines"
        )
    try:
        argv = tuple(shlex.split(pattern, posix=True))
    except ValueError as exc:
        raise ValueError(f"sudo grant has invalid shell quoting: {exc}") from exc
    if not argv:
        raise ValueError("sudo grant must name one exact command")
    if argv[0].startswith("-") or "=" in argv[0]:
        raise ValueError(
            "sudo grant must name the underlying executable, not sudo options "
            "or an environment assignment"
        )
    if os.path.basename(argv[0]).lower() in _PRIVILEGE_WRAPPERS:
        raise ValueError(
            "sudo grant must omit the leading sudo/doas/su wrapper and name "
            "the underlying command"
        )
    for arg in argv:
        if any(ch.isspace() for ch in arg):
            raise ValueError(
                "sudo grant arguments cannot contain embedded whitespace; "
                "split the operation into a simpler exact command"
            )
        if any(ch in arg for ch in _UNSAFE_ARG_CHARS):
            raise ValueError(
                "sudo grant cannot contain wildcards, glob syntax, comments, "
                "backslashes, or shell expansion characters"
            )
    return argv


def normalize_sudo_pattern(pattern):
    """Validate and canonicalize a shell-free exact sudo command."""
    return " ".join(_sudo_argv(pattern))


def sudo_pattern_error(pattern):
    """Return an operator-facing validation error, or an empty string."""
    try:
        _sudo_argv(pattern)
    except ValueError as exc:
        return str(exc)
    return ""


def _sudoers_escape_args(argv):
    """Render exact argv text for sudoers without enabling wildcard matching."""
    if len(argv) == 1:
        # In sudoers, no argument specification means ANY arguments. An
        # explicit empty string is required to authorize no arguments only.
        return ' ""'
    args = " ".join(argv[1:])
    for char in ("\\", ",", ":", "=", "#"):
        args = args.replace(char, "\\" + char)
    if args.startswith("^"):
        args = "\\" + args
    return " " + args


def _resolve_sudo_binary(command):
    """Resolve a root-controlled executable path, or return (None, reason)."""
    binary = shutil.which(command)
    if not binary or not os.path.isabs(binary):
        return None, f"cannot resolve executable '{command}'"
    binary = os.path.realpath(binary)
    try:
        info = os.stat(binary)
    except OSError as exc:
        return None, f"cannot stat executable '{binary}': {exc}"
    if not stat.S_ISREG(info.st_mode):
        return None, f"executable is not a regular file: '{binary}'"
    if info.st_uid != 0 or info.st_mode & (stat.S_IWGRP | stat.S_IWOTH):
        return None, (
            f"executable is not root-owned and protected from non-root writes: "
            f"'{binary}'"
        )

    parent = os.path.dirname(binary)
    while parent:
        try:
            parent_info = os.stat(parent)
        except OSError as exc:
            return None, f"cannot stat executable parent '{parent}': {exc}"
        if (
            parent_info.st_uid != 0
            or parent_info.st_mode & (stat.S_IWGRP | stat.S_IWOTH)
        ):
            return None, (
                f"executable parent is not root-controlled: '{parent}'"
            )
        if parent == os.path.dirname(parent):
            break
        parent = os.path.dirname(parent)
    return binary, ""


def _insert_grant(conn, kind, pattern, note, expires_at, one_time):
    """Insert a grant once, returning (id, created). Caller owns transaction."""
    existing = conn.execute(
        "SELECT id FROM grants WHERE kind=? AND pattern=? AND one_time=? "
        "AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at>=?) "
        "ORDER BY id LIMIT 1",
        (kind, pattern, 1 if one_time else 0, _now()),
    ).fetchone()
    if existing:
        return existing["id"], False
    cur = conn.execute(
        "INSERT INTO grants(kind,pattern,note,created_at,expires_at,one_time) "
        "VALUES(?,?,?,?,?,?)",
        (kind, pattern, note, _now(), expires_at, 1 if one_time else 0),
    )
    _audit(
        conn,
        "grant",
        f"#{cur.lastrowid} {kind}:{pattern}" + (" [one-time]" if one_time else ""),
    )
    return cur.lastrowid, True


# ── checks (called from goethe.py guards) ────────────────────────────────


def _consume_if_one_time(conn, row):
    """A grant created via 'approve --once' is valid for exactly one match.
    Revoke it in the same transaction as the check that used it, so a race
    between two calls can't both slip through on the same one-time grant."""
    if row["one_time"]:
        conn.execute(
            "UPDATE grants SET revoked_at=? WHERE id=? AND revoked_at IS NULL",
            (_now(), row["id"]),
        )
        _audit(conn, "consume-once", f"#{row['id']} {row['kind']}:{row['pattern']}")


def check_path(kind, realpath):
    """kind: 'read'|'write'. realpath: symlink-resolved path (trailing / ok).
    Returns matching grant id, or None. One-time grants are consumed on match."""
    try:
        with _db() as conn:
            p = realpath.rstrip("/") + "/"
            for r in _active(conn, kind):
                pref = (
                    os.path.realpath(os.path.expanduser(r["pattern"])).rstrip("/")
                    + "/"
                )
                if p.startswith(pref):
                    _consume_if_one_time(conn, r)
                    return r["id"]
    except Exception:
        return None
    return None


def check_sudo(command):
    """Match one exact, shell-free command WITHOUT its leading sudo word.

    Unsafe legacy rows are ignored. Returns a grant id or None. One-time
    grants are consumed on match.
    """
    try:
        cmd_argv = _sudo_argv(command)
        with _db() as conn:
            for r in _active(conn, "sudo"):
                try:
                    grant_argv = _sudo_argv(r["pattern"])
                except ValueError:
                    continue
                if cmd_argv == grant_argv:
                    _consume_if_one_time(conn, r)
                    return r["id"]
    except Exception:
        return None
    return None


def file_request(kind, pattern, reason=""):
    """Record a pending grant request (deduped on kind+pattern). Returns id."""
    try:
        if kind == "sudo":
            pattern = normalize_sudo_pattern(pattern)
        with _db() as conn:
            row = conn.execute(
                "SELECT id FROM requests WHERE kind=? AND pattern=? "
                "AND status='pending'",
                (kind, pattern),
            ).fetchone()
            if row:
                return row["id"]
            cur = conn.execute(
                "INSERT INTO requests(kind,pattern,reason,requested_at) "
                "VALUES(?,?,?,?)",
                (kind, pattern, reason, _now()),
            )
            _audit(conn, "request", f"{kind}:{pattern} | {reason}")
            return cur.lastrowid
    except Exception:
        return None


# ── management (goethe-perm CLI) ─────────────────────────────────────────


def grant(kind, pattern, note="", expires_at=None, one_time=False):
    if kind == "sudo":
        pattern = normalize_sudo_pattern(pattern)
    with _db() as conn:
        gid, _created = _insert_grant(
            conn, kind, pattern, note, expires_at, one_time
        )
        return gid


def revoke(gid):
    with _db() as conn:
        n = conn.execute(
            "UPDATE grants SET revoked_at=? WHERE id=? AND revoked_at IS NULL",
            (_now(), gid),
        ).rowcount
        if n:
            _audit(conn, "revoke", f"#{gid}")
        return bool(n)


def list_grants(include_revoked=False):
    with _db() as conn:
        q = "SELECT * FROM grants"
        if not include_revoked:
            q += " WHERE revoked_at IS NULL"
        rows = [dict(r) for r in conn.execute(q + " ORDER BY id")]
    for row in rows:
        if row["kind"] == "sudo":
            error = sudo_pattern_error(row["pattern"])
            row["sudoers_valid"] = not bool(error)
            row["sudoers_error"] = error
    return rows


def pending():
    with _db() as conn:
        rows = [
            dict(r)
            for r in conn.execute(
                "SELECT * FROM requests WHERE status='pending' ORDER BY id"
            )
        ]
    for row in rows:
        if row["kind"] == "sudo":
            error = sudo_pattern_error(row["pattern"])
            row["sudoers_valid"] = not bool(error)
            row["sudoers_error"] = error
    return rows


def resolve_request(rid, approve, note="", once=False):
    """Approve → creates a grant (persistent unless once=True, which consumes
    itself after a single matching use — the 'yes, just this time' case, vs.
    a plain approve which is 'always'). Deny → no grant, request marked denied.
    Returns (status, grant_id|None)."""
    with _db() as conn:
        row = conn.execute(
            "SELECT * FROM requests WHERE id=? AND status='pending'", (rid,)
        ).fetchone()
        if not row:
            return ("not-found", None)
        pattern = row["pattern"]
        if approve and row["kind"] == "sudo":
            # Validate before changing request state. An unsafe legacy request
            # stays pending/deniable instead of becoming an unusable grant.
            pattern = normalize_sudo_pattern(pattern)
        status = "approved" if approve else "denied"
        gid = None
        if approve:
            gid, _created = _insert_grant(
                conn,
                row["kind"],
                pattern,
                note or row["reason"],
                None,
                once,
            )
        conn.execute(
            "UPDATE requests SET status=?, resolved_at=? WHERE id=?",
            (status, _now(), rid),
        )
        _audit(conn, status, f"request #{rid} {row['kind']}:{row['pattern']}")
    return (status, gid)


def sudoers_content():
    """Render sudoers lines for all active sudo grants.

    Unsafe legacy rows are emitted as comments and never as command specs.
    One-time grants are included here so their one matching agent command can
    run without a password; re-run sync after use to remove the stale OS rule.
    """
    lines = [
        "# Managed by goethe-perm — DO NOT EDIT (regenerate: goethe-perm sync-sudoers)"
    ]
    with _db() as conn:
        for r in _active(conn, "sudo"):
            try:
                argv = _sudo_argv(r["pattern"])
            except ValueError as exc:
                lines.append(f"# SKIPPED unsafe grant #{r['id']}: {exc}")
                continue
            binary, error = _resolve_sudo_binary(argv[0])
            if error:
                lines.append(f"# SKIPPED grant #{r['id']}: {error}")
                continue
            lines.append(
                f"{SUDO_RUNAS_USER} ALL=(root) {_NP}: "
                f"{binary}{_sudoers_escape_args(argv)}"
            )
    return "\n".join(lines) + "\n"
