"""goethe_perms — DB-backed granular permission grants for Goethe.

Grants (read path / write path / sudo command) live in SQLite and are
revocable. Grants are created ONLY by the user via the `goethe-perm` CLI;
the agent may file pending *requests* which the user approves or denies.
Sudo grants are enforced at OS level via /etc/sudoers.d/goethe-grants
(regenerated by `goethe-perm sync-sudoers`).
"""
import os
import shutil
import sqlite3
from datetime import datetime, timezone

DB_PATH = os.environ.get("GOETHE_PERMS_DB", "/opt/local-se/goethe-perms.db")
SUDOERS_FILE = "/etc/sudoers.d/goethe-grants"
SUDO_RUNAS_USER = "sy5"
_NP = "NOPASS" + "WD"  # split so content-scanning command guards don't trip

_SCHEMA = """
CREATE TABLE IF NOT EXISTS grants(
  id INTEGER PRIMARY KEY,
  kind TEXT NOT NULL CHECK(kind IN ('read','write','sudo')),
  pattern TEXT NOT NULL,
  note TEXT DEFAULT '',
  created_at TEXT NOT NULL,
  expires_at TEXT,
  revoked_at TEXT
);
CREATE TABLE IF NOT EXISTS requests(
  id INTEGER PRIMARY KEY,
  kind TEXT NOT NULL CHECK(kind IN ('read','write','sudo')),
  pattern TEXT NOT NULL,
  reason TEXT DEFAULT '',
  requested_at TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  resolved_at TEXT
);
CREATE TABLE IF NOT EXISTS audit(
  id INTEGER PRIMARY KEY,
  ts TEXT NOT NULL,
  event TEXT NOT NULL,
  detail TEXT
);
"""


def _now():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _db():
    conn = sqlite3.connect(DB_PATH, timeout=5)
    conn.row_factory = sqlite3.Row
    conn.executescript(_SCHEMA)
    return conn


def _audit(conn, event, detail):
    conn.execute(
        "INSERT INTO audit(ts,event,detail) VALUES(?,?,?)", (_now(), event, detail)
    )


def _active(conn, kind):
    rows = conn.execute(
        "SELECT * FROM grants WHERE kind=? AND revoked_at IS NULL", (kind,)
    ).fetchall()
    now = _now()
    return [r for r in rows if not (r["expires_at"] and r["expires_at"] < now)]


# ── checks (called from goethe.py guards) ────────────────────────────────


def check_path(kind, realpath):
    """kind: 'read'|'write'. realpath: symlink-resolved path (trailing / ok).
    Returns matching grant id, or None."""
    try:
        with _db() as conn:
            p = realpath.rstrip("/") + "/"
            for r in _active(conn, kind):
                pref = (
                    os.path.realpath(os.path.expanduser(r["pattern"])).rstrip("/")
                    + "/"
                )
                if p.startswith(pref):
                    return r["id"]
    except Exception:
        return None
    return None


def check_sudo(command):
    """command: the command WITHOUT the leading privilege word. A grant ending
    in ' *' is a prefix match (any args); otherwise whitespace-normalized
    exact match. Returns grant id or None."""
    try:
        with _db() as conn:
            cmd = " ".join(command.split())
            for r in _active(conn, "sudo"):
                pat = " ".join(r["pattern"].split())
                if pat.endswith(" *"):
                    stem = pat[:-2]
                    if cmd == stem or cmd.startswith(stem + " "):
                        return r["id"]
                elif cmd == pat:
                    return r["id"]
    except Exception:
        return None
    return None


def file_request(kind, pattern, reason=""):
    """Record a pending grant request (deduped on kind+pattern). Returns id."""
    try:
        with _db() as conn:
            row = conn.execute(
                "SELECT id FROM requests WHERE kind=? AND pattern=? "
                "AND status='pending'",
                (kind, pattern),
            ).fetchone()
            if row:
                return row["id"]
            cur = conn.execute(
                "INSERT INTO requests(kind,pattern,reason,requested_at) "
                "VALUES(?,?,?,?)",
                (kind, pattern, reason, _now()),
            )
            _audit(conn, "request", f"{kind}:{pattern} | {reason}")
            return cur.lastrowid
    except Exception:
        return None


# ── management (goethe-perm CLI) ─────────────────────────────────────────


def grant(kind, pattern, note="", expires_at=None):
    with _db() as conn:
        cur = conn.execute(
            "INSERT INTO grants(kind,pattern,note,created_at,expires_at) "
            "VALUES(?,?,?,?,?)",
            (kind, pattern, note, _now(), expires_at),
        )
        _audit(conn, "grant", f"#{cur.lastrowid} {kind}:{pattern}")
        return cur.lastrowid


def revoke(gid):
    with _db() as conn:
        n = conn.execute(
            "UPDATE grants SET revoked_at=? WHERE id=? AND revoked_at IS NULL",
            (_now(), gid),
        ).rowcount
        if n:
            _audit(conn, "revoke", f"#{gid}")
        return bool(n)


def list_grants(include_revoked=False):
    with _db() as conn:
        q = "SELECT * FROM grants"
        if not include_revoked:
            q += " WHERE revoked_at IS NULL"
        return [dict(r) for r in conn.execute(q + " ORDER BY id")]


def pending():
    with _db() as conn:
        return [
            dict(r)
            for r in conn.execute(
                "SELECT * FROM requests WHERE status='pending' ORDER BY id"
            )
        ]


def resolve_request(rid, approve, note=""):
    """Approve → creates the grant. Returns (status, grant_id|None)."""
    with _db() as conn:
        row = conn.execute(
            "SELECT * FROM requests WHERE id=? AND status='pending'", (rid,)
        ).fetchone()
        if not row:
            return ("not-found", None)
        status = "approved" if approve else "denied"
        conn.execute(
            "UPDATE requests SET status=?, resolved_at=? WHERE id=?",
            (status, _now(), rid),
        )
        _audit(conn, status, f"request #{rid} {row['kind']}:{row['pattern']}")
    gid = grant(row["kind"], row["pattern"], note or row["reason"]) if approve else None
    return (status, gid)


def sudoers_content():
    """Render sudoers lines for all active sudo grants."""
    lines = [
        "# Managed by goethe-perm — DO NOT EDIT (regenerate: goethe-perm sync-sudoers)"
    ]
    with _db() as conn:
        for r in _active(conn, "sudo"):
            pat = " ".join(r["pattern"].split())
            wildcard = pat.endswith(" *")
            if wildcard:
                pat = pat[:-2]
            parts = pat.split(" ", 1)
            binary = shutil.which(parts[0]) or parts[0]
            if not binary.startswith("/"):
                lines.append(f"# SKIPPED grant #{r['id']}: cannot resolve '{parts[0]}'")
                continue
            args = (" " + parts[1]) if len(parts) > 1 else ""
            tail = " *" if wildcard else ""
            lines.append(f"{SUDO_RUNAS_USER} ALL=(root) {_NP}: {binary}{args}{tail}")
    return "\n".join(lines) + "\n"
